
package lucot_loginregdb;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

public class SignUp extends javax.swing.JFrame {

    
    public SignUp() {
        initComponents();
        autonumber();
        
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
     private void autonumber(){
        try{
            Connection c = dbConnect.getConnect();
            Statement s = c.createStatement();
            String sql = "SELECT `username`, `password` FROM `registration` WHERE 1";
            ResultSet r = s.executeQuery(sql);
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane,e);
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        firstname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        showpass = new javax.swing.JCheckBox();
        submit = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        showcpass = new javax.swing.JCheckBox();
        password = new javax.swing.JPasswordField();
        cpassword = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SIGN UP");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(90, 0, 99, 42);

        jLabel2.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Firstname:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 90, 70, 17);

        firstname.setPreferredSize(new java.awt.Dimension(64, 25));
        jPanel2.add(firstname);
        firstname.setBounds(20, 110, 243, 30);

        jLabel3.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password: ");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 210, 70, 17);

        showpass.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        showpass.setForeground(new java.awt.Color(255, 255, 255));
        showpass.setText("Show Password");
        showpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpassActionPerformed(evt);
            }
        });
        jPanel2.add(showpass);
        showpass.setBounds(20, 260, 120, 21);

        submit.setBackground(new java.awt.Color(27, 33, 38));
        submit.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        submit.setForeground(new java.awt.Color(255, 255, 255));
        submit.setText("SUBMIT");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jPanel2.add(submit);
        submit.setBounds(80, 400, 133, 36);

        jButton2.setBackground(new java.awt.Color(27, 33, 38));
        jButton2.setFont(new java.awt.Font("Garamond", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("BACK TO HOMEPAGE");
        jButton2.setPreferredSize(new java.awt.Dimension(144, 29));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(70, 450, 160, 30);

        jLabel5.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Confirm Password: ");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 290, 120, 17);

        showcpass.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        showcpass.setForeground(new java.awt.Color(255, 255, 255));
        showcpass.setText("Show Confirm Password");
        showcpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showcpassActionPerformed(evt);
            }
        });
        jPanel2.add(showcpass);
        showcpass.setBounds(20, 340, 170, 21);
        jPanel2.add(password);
        password.setBounds(20, 230, 243, 30);
        jPanel2.add(cpassword);
        cpassword.setBounds(20, 310, 243, 30);

        jLabel6.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Username:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 150, 70, 17);
        jPanel2.add(username);
        username.setBounds(20, 170, 243, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lucot_loginregdb/20231109_144711.jpg"))); // NOI18N
        jPanel2.add(jLabel7);
        jLabel7.setBounds(50, -80, 290, 410);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void showpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpassActionPerformed
        if(showpass.isSelected()){
            password.setEchoChar((char)0);
        }else{
            password.setEchoChar('*');
        }
    }//GEN-LAST:event_showpassActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        String cpass = cpassword.getText();
        String uname = username.getText();
        String pass = password.getText();
        String fname = firstname.getText();
        if(pass.length() < 8 ){
            JOptionPane.showMessageDialog(rootPane, "Password must 8 characters and above!", fname, JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(!pass.matches(".*\\d.*")){
             JOptionPane.showMessageDialog(rootPane, "Password must contain atleast one number!", fname, JOptionPane.ERROR_MESSAGE);
             return;
        }
        if(!pass.equals(cpass)){
            JOptionPane.showMessageDialog(rootPane, "Password and confirm password not equal!", null, JOptionPane.ERROR_MESSAGE);
            return;
        }else{
            try{
                Connection c = dbConnect.getConnect();
                String sql =  "INSERT INTO registration(firstname, username, password) VALUES (?,?,?)";
                PreparedStatement pst = c.prepareStatement(sql);
                pst.setString(1,fname);
                pst.setString(2,uname);
                pst.setString(3,pass);
                pst.executeUpdate();

                //if(i == 1){
                    JOptionPane.showMessageDialog(rootPane, "Record added");
                    firstname.setText("");
                    username.setText("");
                    password.setText("");
                    cpassword.setText("");
                    // }
            }catch(Exception e){
                JOptionPane.showMessageDialog(rootPane, e);
            }
        }

    }//GEN-LAST:event_submitActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        HomeFrame hp = new HomeFrame();
        hp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void showcpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showcpassActionPerformed
        // TODO add your handling code here:
        if(showcpass.isSelected()){
            cpassword.setEchoChar((char)0);
        }else{
            cpassword.setEchoChar('*');
        }
    }//GEN-LAST:event_showcpassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField cpassword;
    private javax.swing.JTextField firstname;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField password;
    private javax.swing.JCheckBox showcpass;
    private javax.swing.JCheckBox showpass;
    private javax.swing.JButton submit;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
